### ISSUE TITLE
Request for the experiment dataset

### ISSUE THREAD

**Issue by Wsy002** [ShiningCosmos/pytorch_ComiRec#4]
Hi, thanks for nice reproduction work. Could you please share the dataset information of the experiment? By the way, why to give up to use the scheduler in the experiment, I'm curious about if it is unnecessary to do so or can use scheduler to get a better performance. I'm an incoming master student with the research interests in Seq Rec. 

Thanks for your time to answer my question.

**Comment by ShiningCosmos** [comment]
Hi,
(1) You can get the dataset from the official repository for the ComiRec (Tensorflow) which is available in https://github.com/THUDM/ComiRec.
(2) About the scheduler, I forget why to give up to use the scheduler. Maybe using the scheduler does not achieve better results. You can try using scheduler and try to get better results.

**Comment by Wsy002** [comment]
> Hi, (1) You can get the dataset from the official repository for the ComiRec (Tensorflow) which is available in https://github.com/THUDM/ComiRec. (2) About the scheduler, I forget why to give up to use the scheduler. Maybe using the scheduler does not achieve better results. You can try using scheduler and try to get better results.

OK thank you for your reply, I will try it first. Have a nice day!

**Comment by Wsy002** [comment]
Hi, I would also like to ask why loss = loss_fn(scores, to_tensor(targets, device)) can use scores and targets for cross-entropy loss. If there is nothing wrong, in my understanding, the scores are the similarity between the final user_emb of each user in a batch and the corresponding label items, and the targets are the tensor corresponding to the label item. I hope you can help me answer this question. Thanks a lot

**Comment by ShiningCosmos** [comment]
For one user, the score is the similarity between the final user_emb and all items (of course, the label item is one of all items), and the target is the ID of the label item. The significance of using cross-entropy loss is to make the similarity between the final user_emb and label item the highest among the similarities between the final user_emb and all items.

**Comment by Wsy002** [comment]
Thanks. By the way, have you ever met this problem that is when I use  faiss gpu to search for the vectors, it works fine in the amazon book dataset, but when I changed to search in taobao dataset, I met this error

"""Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /home/conda/feedstock_root/build_artifacts/faiss-split_1644327811086/work/faiss/gpu/StandardGpuResources.cpp:452: Error: 'err == cudaSuccess' failed: StandardGpuResources: alloc fail type TemporaryMemoryBuffer dev 0 space Device stream 0x5556181f3260 size 1610612736 bytes (cudaMalloc error out of memory [2])"""

The code is running in a GPU cluster with GeForce RTX 2080Ti 11 GB. I also try the faiss search on the google colab pro with P100 , it can also work well in both book data and taobao data.
 Do u know how to solve this?

**Comment by ShiningCosmos** [comment]
There are two possible ways to solve this problem:

1) Put the faiss GPU index and the pytorch model on different GPU devices, for example, put the model and training data on GPU 0, and the faiss GPU index on GPU 1.

2) Use a smaller batch size.

**Comment by Wsy002** [comment]
Thanks so much, I temporarily solved it by reduce the batch size and it works. One more issue, bro, I want to discuss with u that the recall calculation method in the original source code, I notice that in the original code, the author use set() to got the non-repeated label items ( true_item_set = set(iid_list)), then search the target in the I[i], then if iid in true_item_set: recall += 1. After then the author calculate the total_recall by  total_recall += recall * 1.0 / len(iid_list) , Do u think are there any mistakes here?  I also find that it's more reasonable to set(I[i]) then search the result in the label items as what u modified. But i cannot figure out is there any difference between these two method, and whether the changes will take an effect on the acc of computer_diversity function. Thank you for your time.

**Comment by ShiningCosmos** [comment]
1. There may be duplicate items in iid_list, which may be a mistake.
2. For recall, the two methods are the same. But for NDCG, my method is wrong. It has been corrected.

**Comment by Wsy002** [comment]
Hi, want to ask how to output the user multi-interest embedding since the output function can only output item emb, but i cannot figure out how can we get the user interest emb.
